# Generated by Django 2.1.8 on 2020-02-27 13:30

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='pinglun',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('T_pinglun', models.CharField(max_length=32, verbose_name='标题')),
            ],
            options={
                'verbose_name': '评论',
                'verbose_name_plural': '评论',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=32, verbose_name='标题')),
                ('image', models.ImageField(upload_to='media/manager/image', verbose_name='图片')),
                ('text', ckeditor.fields.RichTextField(verbose_name='内容')),
                ('pingllun', models.CharField(max_length=100, verbose_name='评论')),
            ],
            options={
                'verbose_name': '管理员',
                'verbose_name_plural': '管理员',
            },
        ),
    ]
